name: 'Generate changelog with git-chglog'
description: 'Generate a changelog using conventional commits using the git-chlog tool'
branding:
  icon: 'calendar'  
  color: 'green'

inputs:
  config_dir:
    description: 'git-chglog configuration directory'
    default: '.chglog'
    required: true

  filename:
    description: 'Filename to write the changelog to'
    default: 'CHANGELOG.md'
    required: false

  path:
    description: 'Optional path to follow for directory'
    default: ''
    required: false

  tag:
    description: 'Tag to generate the changelog for'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -c
    - ${{ inputs.config_dir }}
    - -o
    - ${{ inputs.filename }}
    - -t
    - ${{ inputs.tag }}
    - -p
    - ${{ inputs.path }}
