name: 'Generate changelog with git-chglog'
description: 'Generate a changelog using conventional commits using the git-chlog tool'
branding:
  icon: 'calendar'  
  color: 'green'

inputs:
  next_version:
    description: 'Next version'
    required: true

  config_dir:
    description: 'git-chglog configuration directory'
    default: '.chglog'
    required: true

  filename:
    description: 'Filename to write the changelog to'
    default: 'CHANGELOG.md'
    required: false

  tag:
    description: Optional, Generate changelog only for this tag.
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -c
    - ${{ inputs.config_dir }}
    - -n
    - ${{ inputs.next_version }}
    - -o
    - ${{ inputs.filename }}
    - -t
    - ${{ inputs.tag }}
